services:
  db:
    image: postgres
    container_name: strings_db_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: strings_backend_container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      CODECOOL_APP_JWTSECRET: ${CODECOOL_APP_JWTSECRET}
      CODECOOL_APP_JWTEXPIRATIONMS: ${CODECOOL_APP_JWTEXPIRATIONMS}
    ports:
      - "8080:8080"
    depends_on:
      - db


volumes:
  postgres_data: